name: Docker Remote Deploy to Proxmox LXC

# 1. Activate each time there's a commit on the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 2. Use self-hosted server, not github servers
    runs-on: self-hosted 
    
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Create .env file for Vite
      - name: Create .env file for Vite
        run: |
          echo "VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }}" > .env
          echo "VITE_ALLOWED_HOST=${{ secrets.VITE_ALLOWED_HOST }}" >> .env

      # Re-build docker container
      - name: Deploy with Docker Compose
        run: |
          docker compose up --build -d